"""init schema: organizations, sites, raw_hrsa_sites

Revision ID: d926f209ad04
Revises: 
Create Date: 2026-05-06 15:38:29.672222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geography
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd926f209ad04'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('legal_name', sa.Text(), nullable=False),
    sa.Column('npi', sa.String(length=10), nullable=True),
    sa.Column('opais_id', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations')),
    sa.UniqueConstraint('npi', name=op.f('uq_organizations_npi')),
    sa.UniqueConstraint('opais_id', name=op.f('uq_organizations_opais_id'))
    )
    op.create_index('ix_organizations_legal_name_trgm', 'organizations', ['legal_name'], unique=False, postgresql_using='gin', postgresql_ops={'legal_name': 'gin_trgm_ops'})
    op.create_table('raw_hrsa_sites',
    sa.Column('source_file', sa.Text(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raw_hrsa_sites'))
    )
    op.create_index('ix_raw_hrsa_sites_source_ingested', 'raw_hrsa_sites', ['source_file', 'ingested_at'], unique=False)
    op.create_geospatial_table('sites',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('bhcmis_id', sa.Text(), nullable=True),
    sa.Column('site_name', sa.Text(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('location', Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_sites_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sites')),
    sa.UniqueConstraint('bhcmis_id', name=op.f('uq_sites_bhcmis_id'))
    )
    op.create_geospatial_index('ix_sites_location', 'sites', ['location'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_sites_organization_id'), 'sites', ['organization_id'], unique=False)
    op.create_index('ix_sites_site_name_trgm', 'sites', ['site_name'], unique=False, postgresql_using='gin', postgresql_ops={'site_name': 'gin_trgm_ops'})
    op.create_index('ix_sites_zip_code', 'sites', ['zip_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sites_zip_code', table_name='sites')
    op.drop_index('ix_sites_site_name_trgm', table_name='sites', postgresql_using='gin', postgresql_ops={'site_name': 'gin_trgm_ops'})
    op.drop_index(op.f('ix_sites_organization_id'), table_name='sites')
    op.drop_geospatial_index('ix_sites_location', table_name='sites', postgresql_using='gist', column_name='location')
    op.drop_geospatial_table('sites')
    op.drop_index('ix_raw_hrsa_sites_source_ingested', table_name='raw_hrsa_sites')
    op.drop_table('raw_hrsa_sites')
    op.drop_index('ix_organizations_legal_name_trgm', table_name='organizations', postgresql_using='gin', postgresql_ops={'legal_name': 'gin_trgm_ops'})
    op.drop_table('organizations')
    # ### end Alembic commands ###
