"""add bhcmis_org_id to organizations and npi to sites

Revision ID: f4c3fd23a27b
Revises: d926f209ad04
Create Date: 2026-05-07 15:28:45.586238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4c3fd23a27b'
down_revision: Union[str, Sequence[str], None] = 'd926f209ad04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('bhcmis_org_id', sa.Text(), nullable=True))
    op.create_unique_constraint(op.f('uq_organizations_bhcmis_org_id'), 'organizations', ['bhcmis_org_id'])
    op.add_column('sites', sa.Column('npi', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_sites_npi'), 'sites', ['npi'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sites_npi'), table_name='sites')
    op.drop_column('sites', 'npi')
    op.drop_constraint(op.f('uq_organizations_bhcmis_org_id'), 'organizations', type_='unique')
    op.drop_column('organizations', 'bhcmis_org_id')
    # ### end Alembic commands ###
